# Generated by Django 5.0.7 on 2024-08-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='profile/default.jpg', upload_to='profile'),
        ),
    ]
