# Generated by Django 5.0.7 on 2024-08-31 12:32

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='profile/default.jpg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 300], upload_to='profile'),
        ),
    ]
