# Generated by Django 5.0.7 on 2024-08-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='book_cover/default.jpg', upload_to='book_cover'),
        ),
    ]
