# Generated by Django 5.0.7 on 2024-09-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_chapter_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='/default/default_book.jpg', upload_to='book_cover'),
        ),
    ]
